/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemeDesignerRouteImport } from './routes/theme-designer'
import { Route as ThemeBuilderRouteImport } from './routes/theme-builder'
import { Route as MvpPreviewRouteImport } from './routes/mvp-preview'
import { Route as IndexRouteImport } from './routes/index'

const ThemeDesignerRoute = ThemeDesignerRouteImport.update({
  id: '/theme-designer',
  path: '/theme-designer',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeBuilderRoute = ThemeBuilderRouteImport.update({
  id: '/theme-builder',
  path: '/theme-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const MvpPreviewRoute = MvpPreviewRouteImport.update({
  id: '/mvp-preview',
  path: '/mvp-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mvp-preview': typeof MvpPreviewRoute
  '/theme-builder': typeof ThemeBuilderRoute
  '/theme-designer': typeof ThemeDesignerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mvp-preview': typeof MvpPreviewRoute
  '/theme-builder': typeof ThemeBuilderRoute
  '/theme-designer': typeof ThemeDesignerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mvp-preview': typeof MvpPreviewRoute
  '/theme-builder': typeof ThemeBuilderRoute
  '/theme-designer': typeof ThemeDesignerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mvp-preview' | '/theme-builder' | '/theme-designer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mvp-preview' | '/theme-builder' | '/theme-designer'
  id: '__root__' | '/' | '/mvp-preview' | '/theme-builder' | '/theme-designer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MvpPreviewRoute: typeof MvpPreviewRoute
  ThemeBuilderRoute: typeof ThemeBuilderRoute
  ThemeDesignerRoute: typeof ThemeDesignerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theme-designer': {
      id: '/theme-designer'
      path: '/theme-designer'
      fullPath: '/theme-designer'
      preLoaderRoute: typeof ThemeDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme-builder': {
      id: '/theme-builder'
      path: '/theme-builder'
      fullPath: '/theme-builder'
      preLoaderRoute: typeof ThemeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mvp-preview': {
      id: '/mvp-preview'
      path: '/mvp-preview'
      fullPath: '/mvp-preview'
      preLoaderRoute: typeof MvpPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MvpPreviewRoute: MvpPreviewRoute,
  ThemeBuilderRoute: ThemeBuilderRoute,
  ThemeDesignerRoute: ThemeDesignerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
